//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSRobaSegonaMa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cloth()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int Id { get; set; }
        public System.DateTime dateCreated { get; set; }
        public bool active { get; set; }
        public int ClothesRequest_Id { get; set; }
        public int Warehouse_Id { get; set; }
        public int Type_Id { get; set; }
        public int Size_Id { get; set; }
        public int Color_Id { get; set; }
        public int Gender_Id { get; set; }
    
        public virtual ClothesRequest ClothesRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual Color Color { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Size Size { get; set; }
        public virtual Type Type { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
