//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSRobaSegonaMa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RobaSegonaMaEntities : DbContext
    {
        public RobaSegonaMaEntities()
            : base("name=RobaSegonaMaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<Cloth> Clothes { get; set; }
        public virtual DbSet<ClothesRequest> ClothesRequests { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<MathOperation> MathOperations { get; set; }
        public virtual DbSet<MaxClaim> MaxClaims { get; set; }
        public virtual DbSet<Name> Names { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderLine> OrderLines { get; set; }
        public virtual DbSet<Requestor> Requestors { get; set; }
        public virtual DbSet<RewardInfoLang> RewardInfoLangs { get; set; }
        public virtual DbSet<Reward> Rewards { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
