//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSRobaSegonaMa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Name
    {
        public int Id { get; set; }
        public int itemId { get; set; }
        public string nameInLanguage { get; set; }
        public string itemType { get; set; }
        public int Language_Id { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
